### PR TITLE
fix: start preview key configuable.

### LINKED ISSUE #2: Conflict keymap via itchyny/vim-qfedit
Problem:

https://github.com/itchyny/vim-qfedit is provide QuickList ediable feature.

But now, confilict keymap `'p'` this plugin and that one. 
It is inconvenient because I cannot put it.

Need and/or Solution:

This plugin will be providing  "preview kick keymap customization".

(`'p'` is natural put keymap, keep it is happy! :)

### PR DESCRIPTION
**Pull request by tsuyoshicho**
Fix #2

### CODE REVIEW

**Comment by bfrg** [comment]
How about we remove the current mapping and provide a `<plug>` mapping? This would be a lot simpler.

Then everyone just assigns it to his favorite key:
```vim
" in after/ftplugin/qf.vim
nmap <buffer> <c-p> <plug>(qf-preview-open)
```

```diff
diff --git a/after/ftplugin/qf.vim b/after/ftplugin/qf.vim
index 04def2c..c9d42f7 100644
--- a/after/ftplugin/qf.vim
+++ b/after/ftplugin/qf.vim
@@ -15,9 +15,9 @@ if exists('g:no_plugin_maps') || !has('patch-8.1.1705')
     finish
 endif
 
-nnoremap <silent> <buffer> p :<c-u>call qfpreview#open(line('.')-1)<cr>
+nnoremap <silent> <buffer> <plug>(qf-preview-open) :<c-u>call qfpreview#open(line('.')-1)<cr>
 
-let b:undo_ftplugin = get(b:, 'undo_ftplugin', 'execute') . '| execute "nunmap <buffer> p"'
+let b:undo_ftplugin = get(b:, 'undo_ftplugin', 'execute') . '| execute "nunmap <buffer> <plug>(qf-preview-open)"'
 
 let &cpoptions = s:save_cpo
 unlet s:save_cpo
```

**Comment by tsuyoshicho** [comment]
OK, good it.

But default mapping is nothing at fine?

**Comment by bfrg** [comment]
Yes, using the `autocmd FileType qf` approach to set buffer-local mappings is also possible.

The `undo_ftplugin` is nevertheless necessary when you change the filetype of the buffer, like `setlocal ft=`. It is very unlikely that someone will do this for the quickfix buffer in the quickfix window, but I consider it good practice to undo every option, mapping and command that a plugin has changed or added.

So technically, we need either:
```vim
" in after/ftplugin/qf.vim
nmap <buffer> <c-p> <plug>(qf-preview-open)
let b:undo_ftplugin .= ' | execute "nunmap <buffer> <c-p>"'
```

Or if you prefer autocommands in your `vimrc`:
```vim
augroup vimrc_ft
    autocmd!
    autocmd FileType qf nmap <buffer> <c-p> <plug>(qf-preview-open)
    autocmd FileType qf let b:undo_ftplugin .= ' | execute "nunmap <buffer> <c-p>"'
augroup END
```

**Comment by tsuyoshicho** [comment]
Oh, QuickFix(buffer) Filetype change. I loss it.

**Comment by bfrg** [comment]
Thank you for your contribution. I have updated the README and documentation a little bit.

**Comment by tsuyoshicho** [comment]
Me too, thanks.

**Pull request merged**
